name: Release

on:
  push:
    tags:
      - v*


jobs:

  build:

    runs-on: windows-latest

    env:
      SOLUTION_NAME: ClearstreamDotNetFramework.sln
      CONFIGURATION: Release 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Restore NuGet Packages
      run: nuget restore ${{ env.SOLUTION_NAME }}

    - name: Build ClearstreamDotNetFramework
      run: msbuild ${{ env.SOLUTION_NAME }} /p:Configuration=${{ env.CONFIGURATION }}
    
    - name: Create NuGet Package
      run: nuget pack -properties Configuration=${{ env.CONFIGURATION }}
      working-directory: ./ClearstreamDotNetFramework/
    
    - name: Push NuGet Package
      run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
      working-directory: ./ClearstreamDotNetFramework/

    
